# .github/workflows/ci-scripts-build.yml for use with EPICS Base ci-scripts
# (see: https://github.com/epics-base/ci-scripts)

# This is YAML - indentation levels are crucial

# Set the 'name:' properties to values that work for you (MYMODULE)

name: omroneip build and test

# Trigger on pushes and PRs to any branch
on:
  push:
    paths-ignore:
      - 'documentation/*'
      - '**/*.html'
      - '**/*.md'
  pull_request:

env:
  SETUP_PATH: .ci-local:.ci

jobs:
  build-base:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    # Set environment variables from matrix parameters
    # Default modules and epics base read in from stable.set
    env:
      CMP: ${{ matrix.cmp }}
      BCFG: ${{ matrix.configuration }}
      LIBPLCTAG: ${{ matrix.libplctag }}
      ASYN: ${{ matrix.asyn }}
      test: ${{ matrix.test }}
      SET: "stable"
    strategy:
      matrix:
        # Job names also name artifacts, character limitations apply
        include:
      #    - os: ubuntu-20.04
      #      cmp: gcc
      #      configuration: static
      #      extra: "CMD_CXXFLAGS=-std=c++23"
      #      name: "Ub-20 C++22, static"
      #      libplctag: "v2.5.3"
      #      asyn: "R4-44-1"
      #      test: "true"

          - os: ubuntu-20.04
            cmp: gcc
            configuration: static
            extra: "CMD_CXXFLAGS=-std=c++11"
            name: "Ub-20 C++11, static"
            libplctag: "v2.5.5"
            base: "7.0"
            test: "true"

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Download and unzip libplctag shared library
      run: |
        python .ci-local/install-libplctag.py
      if: matrix.libplctag != ''
    - name: Prepare and compile dependencies
      run: python .ci/cue.py prepare
    - name: Build main module
      run: python .ci/cue.py build
    - name: Run main module tests
      run: python .ci/cue.py test
    - name: Collect and show test results
      run: python .ci/cue.py test-results
    - name: Build end2end tests
      run: |
        sudo apt-get update
        sudo pip3 install pytest pyepics
    - name: Run end2end tests
      run: |
        python .ci/cue.py exec python iocBoot/iocCITests/runTests.py -s /home/runner/.source/libplctag/${{matrix.libplctag}}/build/bin_dist/ab_server
      if: matrix.test == 'true'