name: omroneip build and publish doxygen documentation
on:
    # Build the docs on pushes to main branch, PRs to main branch, and new tags.
    # Publish only on demand.
    push:
      branches:
        - '*'
      tags:
        - '*'  # all tags
    workflow_dispatch:   # allow manual triggering
      inputs:
        deploy:
          description: 'Deploy documentation'
          type: boolean
          required: true
          default: false

jobs:

    build-docs:
      runs-on: ubuntu-latest
  
      steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 0 # otherwise, you will fail to push refs to dest repo
  
      - name: Install Doxygen
        run: sudo apt-get install doxygen graphviz -y
        shell: bash
  
      - name: Generate Doxygen Documentation
        # Doxygen output is put in _build/html/doxygenHTML by the Doxyfile
        # So it will be published by Publish Jobs below
        run: |
          cd ./docs
          doxygen
          cd ../
  
      - name: Publish Docs
        uses: peaceiris/actions-gh-pages@v3.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/html
          keep_files: true